version: '2.2'
services:
    gitlab:
        image: 'gitlab/gitlab-ce:8.2.0-ce.0'
        container_name: 'gitlab'   
        hostname: gitlab.local.com 
        ports:
            - '80:80'
            - '443:443'
            - '22:22'
            - '587:587'
        volumes:
            - './gitlab/config:/etc/gitlab'
            - './gitlab/logs:/var/log/gitlab'
            - './gitlab/data:/var/opt/gitlab'