version: '3.1'

services:
  mongo:
    image: mongo:4.4.8
    ports:
      - 27017-27019:27017-27019
    environment:
      MONGO_INITDB_DATABASE: database
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
