version: '3'
services:
  oracle-db:
    image: "wnameless/oracle-xe-11g-r2" 
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=true
    ports:
      - '1521:1521'
    expose:
      - '1521'
    # volumes:
    #   - oracle-xe-11g:/var/lib/postgresql/data/ 
# volumes:
#   oracle-xe-11g:

# Connect database with following setting:
# hostname: localhost
# port: 1521
# sid: xe
# username: system
# password: oracle

# Password for SYS & SYSTEM
# oracle