version: '3'
services:
  oracle-db:
    image: "pvargacl/oracle-xe-18.4.0" 
    ports:
      - '1521:1521'
    expose:
      - '1521'

# Connect database with following setting:
# hostname: localhost
# port: 1521
# sid: xe
# username: system
# password: oracle

# Password for SYS & SYSTEM
# oracle