version: '2.2'
services:
  jenkins:
    image: jenkins:2.60.3-alpine
    container_name: jenkins
    ports:
      - 8092:8080
      - 5000:5000
    volumes:
      - jenkins_data:/var/jenkins_home
volumes:
  jenkins_data:
    driver: local