version: '2.2'
services:
  jenkins:
    image: jenkins/jenkins:2.303.1-jdk11
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 8092:8080
      - 5000:5000
    volumes:
      - jenkins_data:/var/jenkins_home
volumes:
  jenkins_data:
    driver: local